# Generated by Django 3.1.7 on 2021-04-30 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0004_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='climatecondition',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.CharField(max_length=300),
        ),
    ]
