# Generated by Django 3.1.7 on 2021-05-04 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0007_smartfar'),
    ]

    operations = [
        migrations.AddField(
            model_name='smartfar',
            name='image',
            field=models.ImageField(default=1, upload_to='uploaded/images'),
            preserve_default=False,
        ),
    ]
