# Generated by Django 3.1.7 on 2021-05-14 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0010_auto_20210509_2351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='customer',
            field=models.CharField(max_length=50),
        ),
    ]
